name: Build,Test and Deploy React Application 
on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
    
jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          npm ci
          npm run jsdoc
          npm run build --if-present
          npm test
      - name: Update Build Version
        id: update_version
        run: echo "BUILD_VERSION=$(date +%Y%m%d)-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}-${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV
      - name: Update README with Build Version
        run: |
          sed -i "s/\(Version actuelle : V\)[0-9]*\.[0-9]*\.[0-9]*/\1${BUILD_VERSION}/" README.md
          sed -i "s/\(version précédente : V\)[0-9]*\.[0-9]*\.[0-9]* → lien/\1${PREVIOUS_VERSION} → [artifact](https://github.com/${GITHUB_REPOSITORY}/actions/runs/${PREVIOUS_RUN_ID})/" README.md
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
        # Upload entire repository
          path: build
          if-no-files-found: error
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
    
  #Deploy job
  deploy:
       # Deploy to thr github-pages environment
       environment:
         name: github-pages
         url: ${{steps.deployment.outputs.page_url}}
       runs-on: ubuntu-latest
       # grant GITHUB_TOKEN the permissions required to make a Page deployment
       permissions:
         pages: write
         id-token: write
       needs: build_test
       steps:
       - name: Deploy to Github Pages
         id: deployment
         uses: actions/deploy-pages@v2
         
      
