name: Build,Test and Deploy React Application 
on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
    
jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          npm ci
          npm run jsdoc
          npm run build --if-present
          npm test
      - name : update versionning
        run: |
          git config --global user.email "balkassechaimaa8@gmail.com"
          git config --global user.name "Chaimaabalk"
          npm -i -g semver
          npm version $(semver 0.1.1 -i prerelease --preid ${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}})
          echo $(semver 0.1.1 -i prerelease --preid ${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}) >> README.md
          git commit -am "new version ${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}} "
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
                path: build
                if-no-files-found: error
    
  #Deploy job
  deploy:
       # Deploy to thr github-pages environment
       environment:
         name: github-pages
         url: ${{steps.deployment.outputs.page_url}}
       runs-on: ubuntu-latest
       # grant GITHUB_TOKEN the permissions required to make a Page deployment
       permissions:
         pages: write
         id-token: write
       needs: build_test
       steps:
       - name: Deploy to Github Pages
         id: deployment
         uses: actions/deploy-pages@v2
      
      
      
